### ISSUE TITLE
Verdictdb 0.5.8 java version is different with the paper "VerdictDB- Universalizing Approximate Query Processing"?

### ISSUE THREAD

**Issue by yanshuyuan** [verdict-project/verdict#390]
I read the verdictdb 0.5.8 java version source code. And I find that the implementation of verdictdb 0.5.8 is not the same as the paper [VerdictDB- Universalizing Approximate Query Processing] said？Do you have an another version implementation of verdictdb?

**Comment by pyongjoo** [comment]
Yes. The current repo has gone through much change since our SIGMOD'18 presentation, to be more automatic/efficient. Still, we are making rapid changes as we have a better understanding of real-world use cases.

FYI, the source code for our old version is still available from https://github.com/verdict-project/verdictdb-sigmod18/tree/old-master
